swagger: '2.0'
info:
  version: "v1"
  title: "choosy-moms-api-${stage}"
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /users:
    x-amazon-apigateway-any-method:
      responses: {}
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        passthroughBehavior: "when_no_match"
        credentials: "${invoker_role}"
        uri: "${users_invocation_arn}"
  /giphy/{proxy+}:
    x-amazon-apigateway-any-method:
      security:
        - api_key: []
      responses: {}
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        passthroughBehavior: "when_no_match"
        credentials: "${invoker_role}"
        uri: "${giphy_invocation_arn}"
